language: go
go:
- 1.8
install:
- go get -v github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
- glide install -v --force
script:
- go get github.com/mitchellh/gox
- gox -osarch="linux/386 linux/amd64 linux/arm darwin/amd64 darwin/386 windows/amd64
  windows/386" -output="out/{{.Dir}}-{{.OS}}-{{.Arch}}" -ldflags "-X github.com/jdel/acdc/cfg.Version=$TRAVIS_TAG"
deploy:
- provider: releases
  overwrite: true
  api_key:
    secure: AxvB3PGNVZI5RjpUeW9d/UvtLJiq9e8E1qnEoNi4peaz+lxF26vx7wtKquE/Qb9OnmYz3xqD6l9IfEp6Ng3htmPTltNHSvryryRLnoiPx6ZAOi1smwpigqUgT4Hc+7xY5AAqSjsKY1TtAKB5JnrY3nztfccJ4TP/jhj93oAhjbiOKlJvB/OdlEyxyCSUzH5aUPgAfWY6n4JAe3FzCxAvmOeuEgCPe5Q/D/d7KzaYOoJ+YTb0SYU528KF6EPSgaY7UwfmDK25M7rj25iz3x4AulMf/tXh+th2AsPmZr8eLI07XYoUn805vmDL7sHW0OhHZGVJqPmnxg3Ua3JhM48/HXHWZxN4AGZGsWM+pctPszlRNmD/GVn7Wzv1gsl0bKZ+e487LJySJM6QASkYg2gPk9xsjgBC7lwXvhrnadzJ8ffHlHLKkqHWV8bKB4S+j/8whg/yb9TViU21t/Tw4P0S15BsisxPvwPGmIvdELbYUyZf1KaxNWDuPGM5519NAYdpNPa7MwmVTYlyZNJvuJVTUOgTHbPJq2BLcb2sSan3FlFJ9eHS6PE9HVC3LtbPpf0ByhR+qcAt8Blawp8mUmvfD+PfdVgBNMNJH+o4b59e2T175r8MjMTmFpmnwlujW+T0UmTn/5z9pVyP7HrnPcTP1CRR2q3zzEnbnUw/NmFtkYI=
  file:
  - out/acdc-darwin-386
  - out/acdc-darwin-amd64
  - out/acdc-linux-386
  - out/acdc-linux-amd64
  - out/acdc-linux-arm
  - out/acdc-windows-386.exe
  - out/acdc-windows-amd64.exe
  skip_cleanup: true
  on:
    repo: jdel/acdc
    tags: true
