language: go
go:
- 1.9
install:
- go get -v github.com/golang/dep/cmd/dep
- go get -v github.com/mitchellh/gox
- cd $GOPATH/src/github.com/golang/dep/cmd/dep && git checkout tags/v0.4.1 && go install
- cd - && dep ensure -v
script:
- gox -osarch="linux/386 linux/amd64 linux/arm darwin/amd64 darwin/386 windows/amd64 windows/386" -output="out/{{.Dir}}-{{.OS}}-{{.Arch}}" -ldflags "-X github.com/jdel/acdc/cfg.Version=$TRAVIS_TAG"

before_deploy:
- gem install dpl -v 1.8.44
deploy:
- provider: bintray
  file: .bintray.json
  user: jdel
  key:
    secure: n9tzMFM/yMSL9l3ZKp0ge4imUmvNZIK6AgeKHsyvbSXXIDcLaG6s5S7DR0/AYoQRRIAcVk2ougWnyOChRgjTdG3/jDMb+a+0bx0PoyvVtAVdbJ6/RgKb+0VIiGp/b1oia4fUkJg90uk1fUsdnAsDBqme1rUcE/UahBZwvPLJxr9eMsjRqBP5+uBvdrWTDAbhiIG/OzW+kQC9CYNalBiuiLwYwwucvVZaHIp3St5qYWYIK6b15E99hH5N+v39/shMiHGhiUdL6llHJaWRA2vvBEOqwc8C39euPDMwA+46+ow3QxYlfzonbiYisvHhBOLDRSK39c8TkvaNbzov9x4ziNvnQ3LPiHtxbWyVmXHfs+KSiL5K4D6ILRPHunqUg6IvdYsH0DnXMWp4N5Xo54PgpvqXe4ai4p1oaF4T0VowDBk80Y7+pr1hZkvpFlHRUvxBHudSbSBVuHLTnCF4/wEXXs2MynwFB741QReaOzbVCl5CT4Yu7l3HuYj5yGhQIyF9Wa0E4Z49iUIQAPZIKaVHcLbtZcxS64tFBG0ES9ogwAbSyuBPjsGaHLkvXQnB3m/h13uzqaU6JTYa1UQzQP9Eb56Am8LpKAKaSIjX9gHNz5CFGYYFr5uJqLmth+n/hBosGbiB9qV9XNQoDlQtytAFf/u0Ia/aW4CgKHo+tBzDSCk=
  on:
    repo: jdel/acdc
    branch: master
- provider: releases
  overwrite: true
  api_key:
    secure: AxvB3PGNVZI5RjpUeW9d/UvtLJiq9e8E1qnEoNi4peaz+lxF26vx7wtKquE/Qb9OnmYz3xqD6l9IfEp6Ng3htmPTltNHSvryryRLnoiPx6ZAOi1smwpigqUgT4Hc+7xY5AAqSjsKY1TtAKB5JnrY3nztfccJ4TP/jhj93oAhjbiOKlJvB/OdlEyxyCSUzH5aUPgAfWY6n4JAe3FzCxAvmOeuEgCPe5Q/D/d7KzaYOoJ+YTb0SYU528KF6EPSgaY7UwfmDK25M7rj25iz3x4AulMf/tXh+th2AsPmZr8eLI07XYoUn805vmDL7sHW0OhHZGVJqPmnxg3Ua3JhM48/HXHWZxN4AGZGsWM+pctPszlRNmD/GVn7Wzv1gsl0bKZ+e487LJySJM6QASkYg2gPk9xsjgBC7lwXvhrnadzJ8ffHlHLKkqHWV8bKB4S+j/8whg/yb9TViU21t/Tw4P0S15BsisxPvwPGmIvdELbYUyZf1KaxNWDuPGM5519NAYdpNPa7MwmVTYlyZNJvuJVTUOgTHbPJq2BLcb2sSan3FlFJ9eHS6PE9HVC3LtbPpf0ByhR+qcAt8Blawp8mUmvfD+PfdVgBNMNJH+o4b59e2T175r8MjMTmFpmnwlujW+T0UmTn/5z9pVyP7HrnPcTP1CRR2q3zzEnbnUw/NmFtkYI=
  file:
  - out/acdc-darwin-386
  - out/acdc-darwin-amd64
  - out/acdc-linux-386
  - out/acdc-linux-amd64
  - out/acdc-linux-arm
  - out/acdc-windows-386.exe
  - out/acdc-windows-amd64.exe
  skip_cleanup: true
  on:
    repo: jdel/acdc
    tags: true
notifications:
  slack:
    secure: eAEEMIGZNxmFoBcUi8Mi21HOeSyS8PhmByzsWxvL8p9Q2uIIAVQfgB3ozUGRWO1/rpXQveCRRx8LEow2YWt/yr1FWBdWXSh2yinB22c5jc7nayThTLK5HIy9KUpRAfEldx/iIudfveBSrw+jHFzvCrNobKuj85bUEExtU3Ro8hs1CsQ09B8laNSuMOqVWBrFKnmqJHATHpRWRL9ILSI1tv/VtclNlrAYGmH7ezgaHkBzsBJr9GbwQHmKNw+OxXuKHs1k9x8mXYkJrJfZIfiupLDyINo+JhVuDDkZdG6M02MlTZsu1YNecuqA8MVMmkI/YhY+snzONZccVNpar0ApE8jDwp5NyasDYDOqFALRNG1FLgPClWnSMOchNYG0SrOlzwN114Pn6E/pKxUu7ncaId/Uhp/vjgYoIVdYMyIcRUJNEC/j43dI/d+EgE+XLN+bSn6J+9JL90M78cHHX8Acjq8kasu/uGwSPig6k7xnUHTfXHGj7+zudComAVgzsFJdgw6fyb5AJ30aQDGVPCB7PgVMZooQVW0Jdh+omFKrNd2rm3Hs/soGrFvJYSWJVlBwMJ4Xp8tDhUsLsHQ/yrrGqmxfNAptqdVzN6SdEfIX7S8XCppdS1+u/jU0sTXjibX2IqNTWdEKYjoOnMAPtwkaOOzzIYSSCe/HtymlJDGd5a0=
