#!/usr/bin/env sh
export GIT_REV_PARSE=$(git rev-parse --short HEAD)
export DOCKER_VERSION=latest
export DOCKER_COMPOSE_VERSION=1.15.0

echo "=-=-=-=-=-=-=- DEBUG INFO =-=-=-=-=-=-=-"
echo "SOURCE_BRANCH: ${SOURCE_BRANCH}"
echo "SOURCE_COMMIT: ${SOURCE_COMMIT}"
echo "COMMIT_MSG: ${COMMIT_MSG}"
echo "DOCKER_REPO: ${DOCKER_REPO}"
echo "DOCKER_TAG: ${DOCKER_TAG}"
echo "IMAGE_NAME: ${IMAGE_NAME}"
echo "GIT_REV_PARSE: ${GIT_REV_PARSE}"
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"

docker build --build-arg ACDC_VERSION=${DOCKER_TAG} \
             --build-arg ACDC_COMMIT=${GIT_REV_PARSE} \
             --build-arg DOCKER_VERSION=${DOCKER_VERSION} \
             --build-arg DOCKER_COMPOSE_VERSION=${DOCKER_COMPOSE_VERSION} \
             -t $IMAGE_NAME .
